derevo1 = new Derevo("Дерево")
derevo1.addAples(3)
console.log(derevo1)
sad1 = new Sad("Сад один")
sad1.addDerevia(3)
console.log(sad1)
sad1.passDay(30)
//sad1.passDay(1)
//sad1.passDay(1)
//sad1.passDay(1)
console.log(sad1)